### ISSUE TITLE
Gostei muito do seu projeto mas falto alguns atributos na pagina.

### ISSUE THREAD

**Issue by Guilherme-alexander** [caickbrito/caickbrito.github.io#1]
Gostei Muito do seu Projeto Senti Falta de Alguns Elementos tipo clik na logo

**Comment by caickbrito** [comment]
Boa tarde, amigo. Obrigado pelo feedback, de fato acredito que cabe mais algumas animações d interações com o usuário, estarei realizando algumas modificações no decorrer dos dias.

**Comment by caickbrito** [comment]
> Gostei Muito do seu Projeto Senti Falta de Alguns Elementos tipo clik na logo 

Boa tarde, amigo. Obrigado pelo feedback, de fato acredito que cabe mais algumas animações e interações com o usuário, estarei realizando algumas modificações no decorrer dos dias.

**Comment by Guilherme-alexander** [comment]
Parabéns Pelo Projeto Bem Criativo 👏🤝
